DSCResources/MSFT_xDnsARecord/MSFT_xDnsARecord.psm1, DSCResources/MSFT_xDnsARecord/MSFT_xDnsARecord.schema.mof, README.md, Tests/xDnsARecord.Tests.ps1
- Fixes #6
- Reads IPv4 address from $record.RecordData.IPv4Address.IPAddressToString property
- Fixes #7:
- Added 'Ensure' parameter to xDnsARecord
- Updated Pester test coverage
- Updated readme.md
=> Added support for removing DNS A records. Fixes #6 and fixes #7

DSCResources/MSFT_xDnsServerPrimaryZone/MSFT_xDnsServerPrimaryZone.psm1, DSCResources/MSFT_xDnsServerPrimaryZone/MSFT_xDnsServerPrimaryZone.schema.mof, README.md, Tests/xDnsServerPrimaryZone.Tests.ps1
* Adds new MSFT_xDnsServerPrimaryZone resource
* Fixes #5 
* Adds test coverage
* Updated readme.md
=> Adds xDnsServerPrimaryZone resource

DSCResources/MSFT_xDnsServerADZone/Helper.psm1, DSCResources/MSFT_xDnsServerADZone/MSFT_xDnsServerADZone.psm1, DSCResources/MSFT_xDnsServerADZone/MSFT_xDnsServerADZone.schema.mof, README.md, Tests/MSFT_xDnsServerADZone.Tests.ps1
xDnsServerADZone allows you to create AD integrated DNS zones. Updated README.md to include documentation and examples for xDnsServerADZone.
=> Added xDnsServerADZone resource and updated README.md

.gitignore, DSCResources/MSFT_xDnsRecord/MSFT_xDnsRecord.psm1, README.md, Tests/Unit/MSFT_xDnsRecord.Tests.ps1
Adds localisation to xDnsRecord
Updates xDnsRecord.Tests.ps1 to use the latest test template
Updates README.md with example round-robin configuration
=> xDnsRecord: Fixed Test-TargetResource function to support array of DNS records. Fixes #23

DSCResources/MSFT_xDnsARecord/MSFT_xDnsARecord.psm1, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/28)
=> Removed hard coding of Localhost computer name to eliminate PSSA rule violation - fixes #26

DSCResources/MSFT_xDnsServerADZone/MSFT_xDnsServerADZone.psm1, README.md, Tests/Unit/MSFT_xDnsServerADZone.Tests.ps1, appveyor.yml, xDnsServer.psd1
Releasing version 1.8.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/52)
=> Release of version 1.8.0.0 of xDnsServer

README.md
- Fixed typo in change log.
- Added contributors to change log.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/70)
=> xDnsServer: Fixed typo in change log and added contributors

.MetaTestOptIn.json, DSCResources/Helper.psm1, DSCResources/MSFT_xDnsARecord/MSFT_xDnsARecord.psm1, DSCResources/MSFT_xDnsServerADZone/MSFT_xDnsServerADZone.psm1, DSCResources/MSFT_xDnsServerForwarder/MSFT_xDnsServerForwarder.psm1, DSCResources/MSFT_xDnsServerPrimaryZone/MSFT_xDnsServerPrimaryZone.psm1, DSCResources/MSFT_xDnsServerSecondaryZone/MSFT_xDnsServerSecondaryZone.psm1, DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.psm1, DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof, DSCResources/MSFT_xDnsServerZoneTransfer/MSFT_xDnsServerZoneTransfer.psm1, Misc/Generate_xDnsServerSetting.ps1, Misc/MockObjects/DnsServerClass.xml, README.md, Tests/Unit/MSFT_xDnsServerADZone.Tests.ps1, Tests/Unit/MSFT_xDnsServerForwarder.Tests.ps1, Tests/Unit/MSFT_xDnsServerSetting.Tests.ps1, Tests/Unit/MSFT_xDnsServerZoneTransfer.Tests.ps1, xDnsServer.psd1
Releasing version 1.10.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/71)
=> Release of version 1.10.0.0 of xDnsServer

DSCResources/MSFT_xDnsServerPrimaryZone/MSFT_xDnsServerPrimaryZone.psm1, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/64)
=> Fix name param to ZoneName in Get-TargetResource - Fixes #63

README.md, appveyor.yml
- Changes to xDsnServer
- Updated appveyor.yml to use the default template and add CodeCov support (issue #73).
- Adding a Branches section to the README.md with Codecov badges for both
master and dev branch (issue #73).
- Updated description of resource module in README.md.
Fixes #73
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/74)
=> xDnsServer: Add CodeCov support

README.md
Clean up the change log a bit so each entry are not shown with blank row after it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/75)
=> Update change log

DSCResources/MSFT_xDnsRecord/MSFT_xDnsRecord.psm1, DSCResources/MSFT_xDnsRecord/MSFT_xDnsRecord.schema.mof, DSCResources/MSFT_xDnsServerPrimaryZone/MSFT_xDnsServerPrimaryZone.psm1, DSCResources/MSFT_xDnsServerZoneAging/MSFT_xDnsServerZoneAging.psm1, DSCResources/MSFT_xDnsServerZoneAging/MSFT_xDnsServerZoneAging.schema.mof, README.md, Tests/Unit/MSFT_xDnsRecord.Tests.ps1, Tests/Unit/MSFT_xDnsServerZoneAging.Tests.ps1, appveyor.yml, xDnsServer.psd1
Releasing version 1.11.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/76)
=> Release of version 1.11.0.0 of xDnsServer

.codecov.yml, .gitattributes, .vscode/analyzersettings.psd1, .vscode/settings.json, README.md, appveyor.yml
* Update appveyor.yml to use the default template.
* Added default template files .codecov.yml, .gitattributes, and .gitignore, and .vscode folder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/81)
=> Update to use template files

DSCResources/MSFT_xDnsServerForwarder/MSFT_xDnsServerForwarder.psm1, DSCResources/MSFT_xDnsServerForwarder/MSFT_xDnsServerForwarder.schema.mof, README.md, Tests/Unit/MSFT_xDnsServerForwarder.Tests.ps1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/82)
=> xDnsServerForwarder : Add UseRootHint

DSCResources/MSFT_xDnsServerZoneScope/MSFT_xDnsServerZoneScope.psm1, DSCResources/MSFT_xDnsServerZoneScope/MSFT_xDnsServerZoneScope.schema.mof, README.md, Tests/Unit/MSFT_xDnsServerZoneScope.Tests.ps1
Added DNS Server Zone Scopes which are part of the DNS Server Policies.
Working on #95 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/102)
=> xDnsServerZoneScope: New Resource

.MetaTestOptIn.json, DSCResources/MSFT_xDnsServerDiagnostics/MSFT_xDnsServerDiagnostics.psm1, DSCResources/MSFT_xDnsServerSecondaryZone/MSFT_xDnsServerSecondaryZone.psm1, DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.psm1, DSCResources/MSFT_xDnsServerZoneScope/MSFT_xDnsServerZoneScope.psm1, DSCResources/MSFT_xDnsServerZoneTransfer/MSFT_xDnsServerZoneTransfer.psm1, README.md
This PR opts in to the following DSC Resource meta tests:
* Common Tests - Relative Path Length
* Common Tests - Validate Markdown Links
* Common Tests - Custom Script Analyzer Rules
* Common Tests - Required Script Analyzer Rules
* Common Tests - Flagged Script Analyzer Rules
To pass the `Common Tests - Custom Script Analyzer Rules` test, the following files had formatting fixed:
* DSCResources/MSFT_xDnsServerSecondaryZone/MSFT_xDnsServerSecondaryZone.psm1
* DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.psm1
* DSCResources/MSFT_xDnsServerZoneTransfer/MSFT_xDnsServerZoneTransfer.psm1
To pass the `Common Tests - Flagged Script Analyzer Rules` test, the following file had verbose messages added:
* DSCResources/MSFT_xDnsServerDiagnostics/MSFT_xDnsServerDiagnostics.psm1
None …
=> xDNSServer: OptIn to Dsc Resource Meta Tests

README.md, Tests/Unit/MSFT_xDnsRecord.Tests.ps1, Tests/Unit/MSFT_xDnsServerADZone.Tests.ps1, Tests/Unit/MSFT_xDnsServerClientSubnet.Tests.ps1, Tests/Unit/MSFT_xDnsServerDiagnostics.Tests.ps1, Tests/Unit/MSFT_xDnsServerForwarder.Tests.ps1, Tests/Unit/MSFT_xDnsServerPrimaryZone.Tests.ps1, Tests/Unit/MSFT_xDnsServerRootHint.Tests.ps1, Tests/Unit/MSFT_xDnsServerSetting.Tests.ps1, Tests/Unit/MSFT_xDnsServerZoneAging.Tests.ps1, Tests/Unit/MSFT_xDnsServerZoneScope.Tests.ps1, Tests/Unit/MSFT_xDnsServerZoneTransfer.Tests.ps1
This PR enables all the unit tests to be run locally, without requiring the `DnsServer` PowerShell module to be installed.
To achieve this, the following changes have been made:
- Added code to load the DnsServer stubs file to all tests that required it.
- Added Mock for `Assert-Module` to all tests that required it.
- Removed partial function stubs that were inline in the tests.
- Added `Set-DnsServerPrimaryZone` mocks to `xDnsServerADZone` tests.
Additionally, trailing spaces were removed from some of the test files.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnss …
=> xDnsServer: Enable Unit Tests to be run Locally

README.md, Tests/Unit/Helper.Tests.ps1
This PR adds unit tests for the following `Helper.psm1` functions:
- Get-LocalizedData
- New-TerminatingError
- Assert-Module
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/112)
=> xDnsServer: Add Missing Helper Module Unit Tests

README.md
This PR fixes the "Removing a DNS A Record" example in `README.md` to reference the `xDnsRecord` resource, rather than the legacy `xDnsARecord` resource.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/113)
=> XDnsServer: Fix "Removing a DNS A Record" example

README.md
This PR fixes the `xDnsServerDiagnostics` `EnableLogFileRollover` Parameter name in `README.md`
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/114)
=> xDnsServer: Fix xDnsServerDiagnostics EnableLogFileRollover Parameter name in README

.MetaTestOptIn.json, Examples/Resources/XDnsServerSecondaryZone/1-xDnsServerSecondaryZone_config.ps1, Examples/Resources/xDnsRecord/1-xDnsRecord_ARecord_config.ps1, Examples/Resources/xDnsRecord/2-xDnsRecord_RoundRobin_config.ps1, Examples/Resources/xDnsRecord/3-xDnsRecord_CName_config.ps1, Examples/Resources/xDnsRecord/4-xDnsRecord_PTR_config.ps1, Examples/Resources/xDnsRecord/5-xDnsRecord_ARecordRemove_config.ps1, Examples/Resources/xDnsServerADZone/1-xDnsServerADZone_forward_config.ps1, Examples/Resources/xDnsServerADZone/2-xDnsServerADZone_reverse_config.ps1, Examples/Resources/xDnsServerClientSubnet/1-xDnsServerClientSubnet_config.ps1, Examples/Resources/xDnsServerConditionalForwarder/1-xDnsServerConditionalForwarder_config.ps1, Examples/Resources/xDnsServerDiagnostics/1-xDnsServerDiagnostics_config.ps1, Examples/Resources/xDnsServerForwarder/1-xDnsServerForwarder_set_config.ps1, Examples/Resources/xDnsServerForwarder/2-xDnsServerForwarder_remove_config.ps1, Examples/Resources/xDnsServerPrimaryZone/1-xDnsServerPrimaryZone_config.ps1, Examples/Resources/xDnsServerRootHint/1-xDnsServerRootHint_set_config.ps1, Examples/Resources/xDnsServerRootHint/2-xDnsServerRootHint_remove_config.ps1, Examples/Resources/xDnsServerSetting/1-xDnsServerSetting_config.ps1, Examples/Resources/xDnsServerZoneAging/1-xDnsServerZoneAging_forward_config.ps1, Examples/Resources/xDnsServerZoneAging/2-xDnsServerZoneAging_reverse_config.ps1, Examples/Resources/xDnsServerZoneScope/1-xDnsServerZoneScope_config.ps1, Examples/Resources/xDnsServerZoneTransfer/1-xDnsServerZoneTransfer_config.ps1, README.md
This PR adds example files for all resources and opts-in to the `Validate Example Files To Be Published` Dsc Resource MetaTest.
Most of the examples have been copied from the `README` and restructured for publishing. The following resources didn't have examples in the `README` so they have been created from scratch:
- xDnsServerClientSubnet
- xDnsServerConditionalForwarder
- xDnsServerDiagnostics
- xDnsServerZoneScope
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/115)
=> xDnsServer: Add Example Files and Optin to the "Validate Example Files To Be Published" DSC Resource MetaTest

.github/ISSUE_TEMPLATE/Problem_with_resource.md, .vscode/settings.json, .vscode/tasks.json, CHANGELOG.md, GitVersion.yml, README.md, RequiredModules.psd1, Resolve-Dependency.ps1, Resolve-Dependency.psd1, azure-pipelines.yml, build.ps1, build.yaml, codecov.yml, source/xDnsServer.psd1
- xDnsServer
- Update pipeline files.
- Renamed the default branch to `main` (issue #131).
- Fixes #131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/132)
=> xDnsServer: Rename the default branch to main

CHANGELOG.md, README.md
Just correcting one label in the readme to "EnableLogFileRollover"
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/128)
=> xDnsServerDiagnostics: Fix typo in README.md for parameter EnableLogFileRollover

CHANGELOG.md, source/DSCResources/MSFT_xDnsServerADZone/MSFT_xDnsServerADZone.psm1, tests/Unit/MSFT_xDnsServerADZone.Tests.ps1
* Fixes bug #79 with proposed solution. 
* Tidy-up of xDnsServer.ps1 ReleasNotes section to improve readability
* Removed references to foreign issues
* Fixes #79 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xdnsserver/80)
=> xDnsServerADZone: bugfix #79

CHANGELOG.md, azure-pipelines.yml
- xDnsServer
- Fix uploading of code coverage that was broken since Sampler had a bug.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/181)
=> xDnsServer: Fix uploading of code coverage

CHANGELOG.md, source/Examples/Resources/xDnsRecord/1-xDnsRecord_ARecord_config.ps1, source/Examples/Resources/xDnsRecord/2-xDnsRecord_RoundRobin_config.ps1, source/Examples/Resources/xDnsRecord/3-xDnsRecord_CName_config.ps1, source/Examples/Resources/xDnsRecord/4-xDnsRecord_PTR_config.ps1, source/Examples/Resources/xDnsRecord/5-xDnsRecord_ARecordRemove_config.ps1, source/Examples/Resources/xDnsServerADZone/1-xDnsServerADZone_forward_config.ps1, source/Examples/Resources/xDnsServerADZone/2-xDnsServerADZone_reverse_config.ps1, source/Examples/Resources/xDnsServerClientSubnet/1-xDnsServerClientSubnet_config.ps1, source/Examples/Resources/xDnsServerConditionalForwarder/1-xDnsServerConditionalForwarder_config.ps1, source/Examples/Resources/xDnsServerForwarder/1-xDnsServerForwarder_set_config.ps1, source/Examples/Resources/xDnsServerForwarder/2-xDnsServerForwarder_remove_config.ps1, source/Examples/Resources/xDnsServerPrimaryZone/xDnsServerPrimaryZone_AddClassfulReversePrimaryZone_Config.ps1, source/Examples/Resources/xDnsServerPrimaryZone/xDnsServerPrimaryZone_AddClasslessReversePrimaryZone_Config.ps1, source/Examples/Resources/xDnsServerPrimaryZone/xDnsServerPrimaryZone_AddPrimaryZoneUsingDefaults_Config.ps1, source/Examples/Resources/xDnsServerPrimaryZone/xDnsServerPrimaryZone_AddPrimaryZoneWithSpecificValues_Config.ps1, source/Examples/Resources/xDnsServerPrimaryZone/xDnsServerPrimaryZone_RemovePrimaryZone_Config.ps1, source/Examples/Resources/xDnsServerPrimaryZone/xDnsServerPrimaryZone_RemoveReversePrimaryZone_Config.ps1, source/Examples/Resources/xDnsServerRootHint/1-xDnsServerRootHint_set_config.ps1, source/Examples/Resources/xDnsServerRootHint/2-xDnsServerRootHint_remove_config.ps1, source/Examples/Resources/xDnsServerSecondaryZone/1-xDnsServerSecondaryZone_config.ps1, source/Examples/Resources/xDnsServerZoneAging/1-xDnsServerZoneAging_forward_config.ps1, source/Examples/Resources/xDnsServerZoneAging/2-xDnsServerZoneAging_reverse_config.ps1, source/Examples/Resources/xDnsServerZoneScope/1-xDnsServerZoneScope_config.ps1, source/Examples/Resources/xDnsServerZoneTransfer/1-xDnsServerZoneTransfer_config.ps1, source/WikiSource/Home.md
- xDnsServer
- Fix examples so the license information point to the correct default branch.
- Updated the prerequisites in the GitHub repository wiki (`Home.md`) that
_Microsoft DNS Server_ is required on a node targeted by a resource, and
that the DSC resources requires the DnsServer PowerShell module (issue #37).
- xDnsServerPrimaryZone
- Added more examples.
- Fixes #37
Was discovered when creating a integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/182)
=> xDnsServerPrimaryZone: Add more examples

CHANGELOG.md, azure-pipelines.yml
- xDnsServer
- Only add required role in integration tests pipeline.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/184)
=> xDnsServer: Update azure pipelines

CHANGELOG.md, tests/Integration/MSFT_xDnsServerPrimaryZone.config.ps1, tests/Integration/MSFT_xDnsServerZoneAging.Integration.Tests.ps1, tests/Integration/MSFT_xDnsServerZoneAging.config.ps1
- xDnsServerZoneAging
- Added integration tests (issue #176).
- Fixes #176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/187)
=> xDnsServerZoneAging: Added integration tests

CHANGELOG.md, source/Classes/002.DnsRecordA.ps1, source/Classes/003.DnsRecordAScoped.ps1, source/Examples/Resources/DnsRecordA/1-DnsRecordA_Mandatory_config.ps1, source/Examples/Resources/DnsRecordA/2-DnsRecordA_Full_config.ps1, source/Examples/Resources/DnsRecordA/3-DnsRecordA_Remove_config.ps1, source/Examples/Resources/DnsRecordAScoped/1-DnsRecordAScoped_Mandatory_config.ps1, source/Examples/Resources/DnsRecordAScoped/2-DnsRecordAScoped_Full_config.ps1, source/Examples/Resources/DnsRecordAScoped/3-DnsRecordAScoped_Remove_config.ps1, source/en-US/DnsRecordA.strings.psd1, source/en-US/DnsRecordAScoped.strings.psd1, tests/Integration/Classes/DnsRecordA.config.ps1, tests/Integration/Classes/DnsRecordA.integration.tests.ps1, tests/Integration/Classes/DnsRecordAScoped.config.ps1, tests/Integration/Classes/DnsRecordAScoped.integration.tests.ps1, tests/Unit/Classes/DnsRecordA.tests.ps1, tests/Unit/Classes/DnsRecordAScoped.tests.ps1, tests/Unit/MockObjects/ARecordInstance.xml
Implements a class-based solution for managing A records - to include implementation of managing records in zone scopes..
- Fixes #145
and comment-based help. **Does not use schema.mof file. Parameter Descriptions not updated in the README.md, as that has moved to the Wiki.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/206)
=> BREAKING CHANGE: DnsRecordA/DnsRecordAScoped: Re-implemented as class-based resources

CHANGELOG.md, RequiredModules.psd1, build.yaml
- xDnsServer
- Updated the pipeline to use new deploy tasks.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/207)
=> xDnsServer: Update pipeline to use new deploy task

CHANGELOG.md, README.md
- xDnsServer
- Fixed a link in the README.md.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/209)
=> xDnsServer: Fix link in README.md

CHANGELOG.md, RequiredModules.psd1, source/Classes/002.DnsRecordCname.ps1, source/Classes/003.DnsRecordCnameScoped.ps1, source/Examples/Resources/DnsRecordCNAME/1-DnsRecordCname_Mandatory_config.ps1, source/Examples/Resources/DnsRecordCNAME/2-DnsRecordCname_Full_config.ps1, source/Examples/Resources/DnsRecordCNAME/3-DnsRecordCname_Remove_config.ps1, source/Examples/Resources/DnsRecordCNAMEScoped/1-DnsRecordCnameScoped_Mandatory_config.ps1, source/Examples/Resources/DnsRecordCNAMEScoped/2-DnsRecordCnameScoped_Full_config.ps1, source/Examples/Resources/DnsRecordCNAMEScoped/3-DnsRecordCnameScoped_Remove_config.ps1, source/en-US/DnsRecordCname.strings.psd1, source/en-US/DnsRecordCnameScoped.strings.psd1, tests/Integration/Classes/DnsRecordCname.config.ps1, tests/Integration/Classes/DnsRecordCname.integration.tests.ps1, tests/Integration/Classes/DnsRecordCnameScoped.config.ps1, tests/Integration/Classes/DnsRecordCnameScoped.integration.tests.ps1, tests/Unit/Classes/DnsRecordCname.tests.ps1, tests/Unit/Classes/DnsRecordCnameScoped.tests.ps1, tests/Unit/MockObjects/CnameRecordInstance.xml
Implements a class-based solution for managing CNAME records - to include implementation of managing records in zone scopes.
Fixes #147 
and comment-based help. **Does not use schema.mof file. Parameter Descriptions not updated in the README.md, as that has moved to the Wiki.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/210)
=> DnsRecordCname/DnsRecordCnameScoped: Re-implemented as class-based resources

CHANGELOG.md, source/Classes/002.DnsRecordSrv.ps1, tests/Unit/Classes/DnsRecordBase.tests.ps1, tests/Unit/Classes/DnsRecordSrv.tests.ps1, tests/Unit/Classes/DnsRecordSrvScoped.tests.ps1
Made some small changes to increase the code coverage of the class-based DNS Records resources
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/215)
=> Increased coverage

CHANGELOG.md, source/Classes/003.DnsRecordAaaa.ps1, source/Classes/004.DnsRecordAaaaScoped.ps1, source/Examples/Resources/DnsRecordAaaa/1-DnsRecordAaaa_Mandatory_config.ps1, source/Examples/Resources/DnsRecordAaaa/2-DnsRecordAaaa_Full_config.ps1, source/Examples/Resources/DnsRecordAaaa/3-DnsRecordAaaa_Remove_config.ps1, source/Examples/Resources/DnsRecordAaaaScoped/1-DnsRecordAaaaScoped_Mandatory_config.ps1, source/Examples/Resources/DnsRecordAaaaScoped/2-DnsRecordAaaaScoped_Full_config.ps1, source/Examples/Resources/DnsRecordAaaaScoped/3-DnsRecordAaaaScoped_Remove_config.ps1, source/en-US/DnsRecordAaaa.strings.psd1, source/en-US/DnsRecordAaaaScoped.strings.psd1, tests/Integration/Classes/DnsRecordAaaa.config.ps1, tests/Integration/Classes/DnsRecordAaaa.integration.tests.ps1, tests/Integration/Classes/DnsRecordAaaaScoped.config.ps1, tests/Integration/Classes/DnsRecordAaaaScoped.integration.tests.ps1, tests/Unit/Classes/DnsRecordAaaa.tests.ps1, tests/Unit/Classes/DnsRecordAaaaScoped.tests.ps1, tests/Unit/MockObjects/AaaaRecordInstance.xml
Implements a class-based solution for managing AAAA records - to include implementation of managing scoped records.
Fixes #146
and comment-based help. **Does not use schema.mof file. Parameter Descriptions not updated in the README.md, as that has moved to the Wiki.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/217)
=> DnsRecordAaaa: Implemented as a class-based resource

CHANGELOG.md
- Add deprecation messages to CHANGELOG:md
- Fixes #220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/222)
=> xDnsServer: Add deprecation messages to CHANGELOG.md

.github/ISSUE_TEMPLATE/Problem_with_resource.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
- xDnsServer
- Fixed the sections in the GitHub issue and pull request templates to
have a bit higher font size. This makes it easier to distinguish the
section headers from the text.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/xdnsserver/226)
=> xDnsServer: Fix GitHub templates

CHANGELOG.md
Move entry that was merged into the wrong location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/249)
=> CHANGELOG: Move entry to correct release

CHANGELOG.md, tests/Unit/DSC_DnsServerADZone.Tests.ps1, tests/Unit/DSC_DnsServerPrimaryZone.Tests.ps1, tests/Unit/Stubs/DnsServer.psm1
- DnsServerDsc
- Updated stub function to throw if they are used (instead of being mocked) (issue #235).
- Fixes #235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/250)
=> DnsServerDsc: Updated stub functions to throw

CHANGELOG.md, azure-pipelines.yml, build.yaml, codecov.yml
- DnsServerDsc
- Fixed code coverage in the pipeline (issue #246).
- Fixes #246
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/253)
=> DnsServerDsc: Fixed code coverage in the pipeline

CHANGELOG.md, source/Classes/001.ResourceBase.ps1, source/Classes/003.DnsServerDsSetting.ps1, source/Examples/Resources/DnsServerDsSetting/1-DnsServerDsSetting_DirectoryPartitionAutoEnlistInterval_Config.ps1, source/Examples/Resources/DnsServerDsSetting/2-DnsServerDsSetting_LazyUpdateInterval_Config.ps1, source/Examples/Resources/DnsServerDsSetting/3-DnsServerDsSetting_MinimumBackgroundLoadThreads_Config.ps1, source/Examples/Resources/DnsServerDsSetting/4-DnsServerDsSetting_PollingInterval_Config.ps1, source/Examples/Resources/DnsServerDsSetting/5-DnsServerDsSetting_RemoteReplicationDelay_Config.ps1, source/Examples/Resources/DnsServerDsSetting/6-DnsServerDsSetting_TombstoneInterval_Config.ps1, source/Examples/Resources/DnsServerDsSetting/7-DnsServerDsSetting_All_Config.ps1, source/en-US/DnsServerDsSetting.strings.psd1, tests/Integration/Classes/DnsServerDsSetting.Integration.Tests.ps1, tests/Integration/Classes/DnsServerDsSetting.config.ps1, tests/Unit/Classes/DnsServerDsSetting.Tests.ps1
Implements Get-DnsServerDsSetting and Set-DnsServerDsSetting as a DSC resource.
- Fixes #251
- [N/A] Resource documentation added/updated in README.md.
- [N/A] Resource parameter descriptions added/updated in README.md, schema.mof
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/258)
=> DnsServerDsSetting: New Resource to Manage AD DNS settings

.github/ISSUE_TEMPLATE/Problem_with_resource.yml, .github/ISSUE_TEMPLATE/Resource_proposal.yml, CHANGELOG.md, source/WikiSource/Home.md
- DnsServerDsc
- Updated wiki start page with deprecation notice.
- Updated issue template for proposing a new resource.
Closes #238 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/267)
=> DnsServerDsc: Update wiki and GitHub issue template

CHANGELOG.md, tests/Unit/Classes/DnsRecordBase.tests.ps1, tests/Unit/Classes/ResourceBase.Tests.ps1
- DnRecordBase
- Update comment regarding use of `using module` statement.
- ResourceBase
- Update comment regarding use of `using module` statement.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/269)
=> Fix comment regarding `using module`

CHANGELOG.md, azure-pipelines.yml, debug.ps1
- DnsServerDsc
- Removed left-over debug code.
- Update to use the build worker `windows-latest` for the necessary stages
of the pipeline, and `ubuntu-latest` for the other stages.
- Update pipeline to use _GitVersion.Tool_ installed by `dotnet`.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/dnsserverdsc/270)
=> DnsServerDsc: Remove left-over debug code

CHANGELOG.md, source/Modules/DnsServerDsc.Common/DnsServerDsc.Common.psd1, tests/Unit/DnsServerDsc.Common.Tests.ps1
- DnsServerDsc.Common
- Added unit tests for `Convert-RootHintsToHashtable`.
- Removed unit tests for functions no longer part of the module.
- Removed functions from the module manifest that are no longer
part of the module.
None.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/271)
=> Update DnsServerDsc.Common module and unit tests

CHANGELOG.md, RequiredModules.psd1, build.yaml, source/DSCResources/DSC_DnsServerADZone/DSC_DnsServerADZone.psm1
Update `build.yaml` key `Generate_Wiki_Content` to `Generate_Markdown_For_DSC_Resources` to remove warning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/277)
=> Fix build warning

CHANGELOG.md, tests/Unit/DSC_DnsServerClientSubnet.Tests.ps1
fix wrong SYNAPSIS in DSC_DnsServerClientSubnet.Tests.ps1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/DnsServerDsc/288)
=> Fix wrong SYNAPSIS in DSC_DnsServerClientSubnet.Tests.ps1
